In [1]:
import pandas as pd
import numpy as np
#import seaborn as sns

C:\Users\peiyaozhao\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

## Main Task
- Write a function that takes in the uncertainty vector (i.e. a vector of the 9 proportions) and then computes total emissions
- The above function may be made up several subroutines/subfunctions that compute specific sectors (as you've already done below)
- Similarly, the function may return sector-specific emissions, as well, for future analysis
- Apply this function to samples_df (without using a loop) in order to compute the following columns: emissions, % change from baseline, and then columns for each of the sectors that change (those that do not change can be combined into something called "Other" (i.e. waste, agro, etc)
- Save the dataframe as `results/futures-ensemble.csv`

In [8]:
samples_df = pd.read_csv("../../results/lhs-samples.csv")

samples_df

,Car VMT,Truck VMT,Car MPG,E-grid Emissions Factor,Residential Electricity,Commercial/Industrial Electricity,Residential Fuel Oil,Residential Propane,Residential Natural Gas
0,-0.883453,-0.968493,0.968571,-0.036055,0.098391,0.399692,-0.414664,-0.249818,0.027631
1,0.189026,-0.872364,0.021911,-0.880397,-0.118682,0.062959,-0.845384,-0.586233,0.218740
2,-0.557899,-0.593396,0.745836,0.218997,0.009903,0.115637,-0.419767,0.231621,0.436630
3,-0.817005,-0.165899,1.385298,-0.089012,-0.443197,0.048547,0.391044,-0.671720,0.269572
4,-0.751856,-0.482377,0.137666,0.247450,0.397856,-0.071258,-0.337105,-0.555747,-0.975525
...,...,...,...,...,...,...,...,...,...
9995,-0.732641,-0.400085,1.410568,0.145053,0.040789,-0.084889,0.456933,-0.588166,-0.192500
9996,-0.043476,-0.074621,1.332716,-0.843953,0.069569,0.416541,0.146355,-0.529009,-0.571508
9997,-0.601524,-0.833698,0.805559,-0.448116,-0.152931,-0.136956,-0.668707,0.476813,-0.781565
9998,-0.042417,-0.275202,0.444039,-0.140701,0.075548,0.106064,0.355701,-0.087215,0.320251
9999,-0.468182,-0.587985,0.644175,0.387931,0.398054,0.318353,-0.191581,-0.783999,0.412970

In [3]:
emissions = pd.read_excel('../../data/tidy/Emissions-Reduction-Calculation.xlsx')
activity = pd.read_csv('../../results/sectors/NewHaven-Emissions-Summary.csv')
activity

,Year,Sector,Subsector,Activity Data Description,Activity Data Unit,Activity Data,GHG Emissions (MMTCO2e),Population,Emissions per Capita (MTCO2e)
0,2021,Mobile Combustion,Automobile,Vehicle Miles Traveled,Billion Miles,2.806589,1.028899,864751,1.189821
1,2021,Mobile Combustion,Motorcycle,Vehicle Miles Traveled,Billion Miles,0.208674,0.036643,864751,0.042374
2,2021,Mobile Combustion,Trucks,Vehicle Miles Traveled,Billion Miles,3.870990,1.789613,864751,2.069512
3,2021,Mobile Combustion,Buses,Vehicle Miles Traveled,Billion Miles,0.025632,0.020234,864751,0.023399
4,2021,Electricity Consumption,Residential,Electricity Consumption,TWh,2.481066,0.612048,864751,0.707773
5,2021,Electricity Consumption,Commercial/Industrial,Electricity Consumption,TWh,2.849325,0.702893,864751,0.812827
6,2021,Solid Waste,Waste Combustion,Waste Combustion Emissions,,NaN,0.000000,864751,0.000000
7,2021,Solid Waste,Landfill Emissions,Landfills Emissions,,NaN,0.000000,864751,0.000000
8,2020,Stationary Combustion,Residential,Household Heating Oil Consumption,Million Gallon,74.623292,0.759970,855733,0.888093
9,2020,Stationary Combustion,Residential,Household Propane Consumption,Million Gallon,9.975587,0.057276,855733,0.066932
10,2020,Stationary Combustion,Residential,Household Natural Gas Consumption,Million cf,9988.504497,0.543774,855733,0.635448
11,2020,Stationary Combustion,Commercial,Commercial Building Footprint,Unitless Ratio,0.249936,0.955882,855733,1.117033
12,2020,Stationary Combustion,Industrial,NaN,,NaN,0.339402,855733,0.396621
13,2017,Agriculture & Land management,Organic Fertilizer,Organic Fertilizer Land Area,Acres,173.000000,0.000099,862127,0.000115
14,2017,Agriculture & Land management,Synthetic Fertilizer,Synthetic Fertilizer Land Area,Acres,3764.000000,0.029055,862127,0.033702
15,2017,Agriculture & Land management,Manure Fertilizer,Manure Fertilizer Land Area,Acres,1125.000000,0.000087,862127,0.000101
16,2021,Wastewater Treatment,Wastewater Facility,Waste Water Facility,Unitless Ratio,0.238095,0.092857,864751,0.107380
17,2015,Forestry,Deciduous Forest,Deciduous Forest Area,Thousand Hectare,66.913058,-0.547126,862224,-0.634552
18,2015,Forestry,Coniferous Forest,Coniferous Forest Area,Thousand Hectare,5.263043,-0.043034,862224,-0.049911
19,2015,Forestry,Forested Wetland,Forested Wetland Area,Thousand Hectare,4.614511,-0.037731,862224,-0.043760

In [4]:
# Remove rows starting from index 20
emissions = emissions.iloc[:20]

# Keep only the first four columns
emissions = emissions.iloc[:17, :4]
emissions

,Sector,Subsector,Year,Total Emissions (MMTCO2e)
0,Mobile Combustion,Automobile,2021.0,1.028899
1,Mobile Combustion,Motorcycle,2021.0,0.036643
2,Mobile Combustion,Trucks,2021.0,1.789613
3,Mobile Combustion,Buses,2021.0,0.020234
4,Electricity Consumption,Residential Electricity,2021.0,0.612048
5,Electricity Consumption,Commercial&Industrial Electricity,2021.0,0.702893
6,Solid Waste Landfills,Landfill fuel combustion,2021.0,0.000000
7,Solid Waste Landfills,Landfill methane,2021.0,0.000000
8,Stationary Combustion,Residential fuel oil,2020.0,0.760000
9,Stationary Combustion,Residential natural gas,2020.0,0.540000
10,Stationary Combustion,Residential propane,2020.0,0.060000
11,Stationary Combustion,Commercial fuel,2020.0,0.960000
12,Stationary Combustion,Industrial fuel,2020.0,0.339402
13,Agriculture & Land management,Organic fertilizer,2017.0,0.000099
14,Agriculture & Land management,Synthetic fertilizer,2017.0,0.029055
15,Agriculture & Land management,Manure fertilizer,2017.0,0.000087
16,Wastewater treatment,Wastewater,2021.0,0.092857

In [5]:
sum_emissions = emissions["Total Emissions (MMTCO2e)"].sum()

In [6]:
# EFGG = [EFcar,EFmotor,EFtruck,EFbus,EFe,Qrs,EFr,Qrc,Qri,Qra,Qrw]
#R represents a constant and it means mpg here: passenger_car gasoline, light truck diesel, heavy duty diesel, motorcycle gasoline
#gasoline, diesel, CH4 and N20 for gaso_passenger, gaso_motorcycle, bus, truck individually
Et = emissions['Total Emissions (MMTCO2e)'].tolist()
Qa = activity['Activity Data'].tolist()

In [7]:
# Merge the two dataframes on the 'Parameter' column
df = pd.merge(uncertainty_df_continuous, activity_df, on='Parameter')

# Function to calculate percentage change for each value in the Uncertainty Distribution
def calculate_percentage_change(row):
    baseline_value = row['Baseline Activity Value']
    return [(x - baseline_value) / baseline_value * 100 for x in row['Uncertainty Distribution']]

# Apply the function to each row and create new columns for the percentage change
df['Uncertainty % Change'] = df.apply(calculate_percentage_change, axis=1)

# Display the updated dataframe
df[['Parameter', 'Uncertainty Distribution', 'Uncertainty % Change']]

NameError: name 'uncertainty_df_continuous' is not defined

In [ ]:
EFmco2_gasoline = 8.78 
EFmco2_diesel = 10.21
EFmch4_car = 0.008
EFmn2o_car =0.007
EFmch4_motorcycle = 0
EFmn2o_motorcycle = 0 
EFmch4_buses = 0.005
EFmn2o_buses = 0.005
EFmch4_trucks = 0.001
EFmn2o_trucks = 0.001 
EFer_oil = 10150+ 0.41*25+0.08*298
EFer_propane = 5720+0.27*25+0.05*298
EFer_naturalgas = 54.44

In [ ]:
# VMT_car = uncertainty_df_continuous['Uncertainty Distribution'][0]
# VMT_trucks  = uncertainty_df_continuous['Uncertainty Distribution'][1]

# mpg_car = uncertainty_df_continuous['Uncertainty Distribution'][2]

# EFee = uncertainty_df_continuous['Uncertainty Distribution'][3]
# Qre = uncertainty_df_continuous['Uncertainty Distribution'][4]
# Qce = uncertainty_df_continuous['Uncertainty Distribution'][5]

# Qrfuel = uncertainty_df_continuous['Uncertainty Distribution'][6]
# Qrpropane = uncertainty_df_continuous['Uncertainty Distribution'][7]
# Qrgas = uncertainty_df_continuous['Uncertainty Distribution'][8]

In [ ]:
Eim_car = emissions['Total Emissions (MMTCO2e)'][0]
Eim_motorcycle = emissions['Total Emissions (MMTCO2e)'][1]
Eim_trucks = emissions['Total Emissions (MMTCO2e)'][2]
Eim_buses = emissions['Total Emissions (MMTCO2e)'][3]
Ei_r_e = emissions['Total Emissions (MMTCO2e)'][4]
Ei_c_e = emissions['Total Emissions (MMTCO2e)'][5]

Ei_r_oil = emissions['Total Emissions (MMTCO2e)'][8]
Eim_r_gas = emissions['Total Emissions (MMTCO2e)'][9]
Eim_r_propane = emissions['Total Emissions (MMTCO2e)'][10]
Eim_commr = emissions['Total Emissions (MMTCO2e)'][11]
Eim_indus = emissions['Total Emissions (MMTCO2e)'][12]
Eim_organic = emissions['Total Emissions (MMTCO2e)'][13]
Eim_synthetic = emissions['Total Emissions (MMTCO2e)'][14]
Eim_manure = emissions['Total Emissions (MMTCO2e)'][15]
Eim_waste = emissions['Total Emissions (MMTCO2e)'][16]

In [ ]:
#mobile combustion
def model_emissions_Em(VMT,mpg,EFmco2,EFmch4,EFmn2o):
    Em = (VMT*1000000*EFmco2/mpg+VMT*EFmch4*1000*25+VMT*EFmn2o*1000*25)/1000000
    return Em

#electricity consumption, residential consumption
def model_emissions_Eer(Qe,EFe):
    Ee = Qe*EFe/2204.62
    return Ee

# residential consumption
def model_emissions_Er(Qe,EFe):
    Ee = Qe*EFe/1000000
    return Ee

Erest = Eim_commr+Eim_indus+Eim_organic+Eim_synthetic+Eim_manure+Eim_waste

In [ ]:
#mobile emissions
Emissions_mobile_car_vmt = model_emissions_Em(VMT_car, mpg_car, EFmco2_gasoline, EFmch4_car,EFmn2o_car)
Emissions_mobile_trucks_vmt = model_emissions_Em(VMT_trucks, 22.1, EFmco2_diesel,EFmch4_trucks,EFmn2o_trucks)
Emissions_mobile_buses_motorcycle = Eim_motorcycle+Eim_buses

#electricity consumption emissions
Emissions_electricity_residential= model_emissions_Eer(Qre,EFee)
Emissions_electricity_commercial_industrial = model_emissions_Eer(Qce,EFee)

# Emissions_electricity_residential_Q= model_emissions_Eer(Ei_r_e,Qre,543.852)
# Emissions_electricity_commercial_industrial_Q = model_emissions_Eer(Ei_c_e,Qce,543.852)

#stationary combustion emissions
Emissions_residential_oil= model_emissions_Er(Qrfuel,EFer_oil)
Emissions_residential_propane = model_emissions_Er(Qrpropane,EFer_propane)
Emissions_residential_gas= model_emissions_Er(Qrgas,EFer_naturalgas)

Etotal = Emissions_mobile_car_vmt+Emissions_mobile_trucks_vmt+Emissions_mobile_buses_motorcycle+Emissions_electricity_residential+Emissions_electricity_commercial_industrial+Emissions_residential_oil+Emissions_residential_propane+Emissions_residential_gas+Erest

#Etotal
Etotal

# Compute final values
Epercent = (sum_emissions - Etotal) / sum_emissions * 100

In [ ]:
plt.hist(Etotal, bins=100, edgecolor='black', alpha=0.7)

In [ ]:
plt.hist(Epercent, bins=100, edgecolor='black', alpha=0.7)

#emissions reduction versus variables
#lolipoop: how much emisisons reduction/change by the change of each parameter (by lolipop/tornado plot)---go to prim

In [ ]:
df_final['Emissions (MMTCO2e)'] = Etotal
df_final['Emissions Percent Change (%)'] = Epercent

In [ ]:
df_final

df = df_final[df_final.columns[:9]]
response = df_final['Emissions Percent Change (%)']

p = prim.Prim(df, response, threshold=-50, threshold_type="<")

box = p.find_box()

box.show_tradeoff()

plt.show()