In [1]:
import pandas as pd
import numpy as np
import os
import string
from scipy.stats import qmc

In [5]:
# Number of samples you want to generate
num_samples = 10000  # You can adjust this
num_uncertainties = 9 #(10 dimensions, one for each parameter)

# Initialize the Latin Hypercube Sampling generator 
sampler = qmc.LatinHypercube(d=num_uncertainties, seed=42)  # 
lhs_samples = sampler.random(n=num_samples)  # Generate random samples

In [6]:
bounds = pd.read_csv('../../data/tidy/uncertainty-ranges.csv')
bounds

                           Parameter   LB   UB
0                            Car VMT -1.0  0.2
1                          Truck VMT -1.0  0.2
2                            Car MPG  0.0  1.5
3            E-grid Emissions Factor -1.0  0.5
4            Residential Electricity -0.5  0.5
5  Commercial/Industrial Electricity -0.2  0.5
6               Residential Fuel Oil -1.0  0.5
7                Residential Propane -1.0  0.5
8            Residential Natural Gas -1.0  0.5

In [7]:
samples = qmc.scale(lhs_samples, bounds.LB, bounds.UB)
samples_df = pd.DataFrame(samples)
samples_df.columns = bounds.Parameter
samples_df

Parameter,Car VMT,Truck VMT,Car MPG,E-grid Emissions Factor,Residential Electricity,Commercial/Industrial Electricity,Residential Fuel Oil,Residential Propane,Residential Natural Gas
0,-0.883453,-0.968493,0.968571,-0.036055,0.098391,0.399692,-0.414664,-0.249818,0.027631
1,0.189026,-0.872364,0.021911,-0.880397,-0.118682,0.062959,-0.845384,-0.586233,0.218740
2,-0.557899,-0.593396,0.745836,0.218997,0.009903,0.115637,-0.419767,0.231621,0.436630
3,-0.817005,-0.165899,1.385298,-0.089012,-0.443197,0.048547,0.391044,-0.671720,0.269572
4,-0.751856,-0.482377,0.137666,0.247450,0.397856,-0.071258,-0.337105,-0.555747,-0.975525
...,...,...,...,...,...,...,...,...,...
9995,-0.732641,-0.400085,1.410568,0.145053,0.040789,-0.084889,0.456933,-0.588166,-0.192500
9996,-0.043476,-0.074621,1.332716,-0.843953,0.069569,0.416541,0.146355,-0.529009,-0.571508
9997,-0.601524,-0.833698,0.805559,-0.448116,-0.152931,-0.136956,-0.668707,0.476813,-0.781565
9998,-0.042417,-0.275202,0.444039,-0.140701,0.075548,0.106064,0.355701,-0.087215,0.320251
9999,-0.468182,-0.587985,0.644175,0.387931,0.398054,0.318353,-0.191581,-0.783999,0.412970

In [8]:
samples_df.to_csv('../../results/lhs-samples.csv', index=False)